mariadb:
  image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-mariadb:10.6.4-focal
  app: mariadb
  storage: 1Gi
  dbPassword: yarin123
  dbUsername: yarin

wordpress:
  replicaCount: 2
  app: wordpress
  image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-wordpress:latest
  port: 80
  dbhost: mariadb

ingress:
  enabled: true
  host: wordpress.local
  path: /
